### ISSUE TITLE
Unable to install Shortcode 

### ISSUE THREAD

**Issue by AlyxTaj** [Daniel-KM/Omeka-S-module-Shortcode#2]
Hello Daniel,

I'm working on an Omeka website I've updated to version 4.0.0, I get an error trying to install the Shortcode module.

`Error: Call to a member function get() on null in /home/alyxtjfreq/www/modules/Shortcode/data/scripts/upgrade_vocabulary.php:29 Stack trace: #0 /home/alyxtjfreq/www/modules/Shortcode/Module.php(52): require_once() #1 /home/alyxtjfreq/www/modules/Generic/AbstractModule.php(77): Shortcode\Module->preInstall() #2 /home/alyxtjfreq/www/application/src/Module/Manager.php(226): Generic\AbstractModule->install(Object(Laminas\ServiceManager\ServiceManager)) #3 /home/alyxtjfreq/www/application/src/Controller/Admin/ModuleController.php(117): Omeka\Module\Manager->install(Object(Omeka\Module\Module)) #4 /home/alyxtjfreq/www/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Omeka\Controller\Admin\ModuleController->installAction() #5 /home/alyxtjfreq/www/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent)) #6 /home/alyxtjfreq/www/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure)) #7 /home/alyxtjfreq/www/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent)) #8 /home/alyxtjfreq/www/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response)) #9 /home/alyxtjfreq/www/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent)) #10 /home/alyxtjfreq/www/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure)) #11 /home/alyxtjfreq/www/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent)) #12 /home/alyxtjfreq/www/index.php(21): Laminas\Mvc\Application->run() #13 {main}`

Here is my configuration
`<html><body>

Omeka S
--
4.0.0

8.1.6
fpm-fcgi
512M
130M
128M
Yes
bcmath, bz2, calendar, cgi-fcgi, Core, ctype, curl,  date, dba, dom, exif, FFI, fileinfo, filter, ftp, gd, gettext, gmp,  hash, iconv, imagick, imap, intl, json, libxml, mbstring, memcached,  mongodb, mysqli, mysqlnd, openssl, pcre, PDO, pdo_mysql, pdo_pgsql,  pdo_sqlite, pgsql, Phar, posix, pspell, redis, Reflection, session,  SimpleXML, soap, sockets, sodium, SPL, sqlite3, standard, sysvmsg,  sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, Zend  OPcache, zip, zlib
dl, _dyuweyrj4, _dyuweyrj4r

5.7.41-log
mysqlnd 8.1.6
NO_ENGINE_SUBSTITUTION

Linux 5.15.80-ovh-vps-grsec-zfs-classid x86_64

Advanced Search (3.4.6.20), Block Plus (3.4.15.9),  Bulk Edit (3.4.18), Bulk Import (3.4.38), CSSEditor (1.3.1), CSV Import  (2.4.1), Clean Url (3.17.4.4), Easy Admin (3.4.9.2), Extract Text  (1.3.0), Generic module (3.4.42), Hide Properties (1.3.1), Log (3.4.13),  Mapping (1.8.0), Numeric Data Types (1.10.0), Reference (3.4.40)
Extract Metadata (1.1.0)
Shortcode (3.4.1.10)

/usr/local/php8.1/bin/php
[invalid]

</body>
</html>`

Thanks in advance !

**Comment by AlyxTaj** [comment]
fyi
I inserted the module directly into the module table of the database and now it seems to be working.
